plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
# this version will render table properly https://github.com/orgs/community/discussions/23945
title: Python/Git Workshop
markdown: GFM
show_downloads: true
google_analytics: G-966JZZV0M0
theme:   jekyll-theme-midnight


# jekyll-theme-minimal     <-- blue
# jekyll-theme-hacker      <-- black background with typewriter font
# jekyll-theme-architect   <-- handwriting-like font
# jekyll-theme-merlot      <-- scrolls as decorations
# jekyll-theme-cayman      <-- green/blue top banner 
# jekyll-theme-midnight    <-- dark
#
# others:                  <-- https://github.com/pages-themes
